const express = require('express')
const cors = require('cors')
const multipart = require('connect-multiparty')
const md_auth = require("../middlewares/authenticated")
const MascotaController = require("../controllers/mascotaController")
const api = express.Router();
const md_upload = multipart({ uploadDir: './uploads/fotosMascotas' })
api.use(cors())
api.post("/nueva", [md_auth.ensureAuth,md_upload], MascotaController.createMascota)
api.get("/getFromUser", [md_auth.ensureAuth], MascotaController.getMascotasFromUser)
api.get("/mascotas", MascotaController.getMascotas)
api.get("/fotoMascota/:id", MascotaController.getFoto)
api.get("/mascota/:id", MascotaController.getMascota)
api.put("/mascota/:id", MascotaController.editMascota)
api.delete("/mascota/:id", MascotaController.delMascota)
module.exports = api;